### ISSUE TITLE
Tamaño de los identificadores de los carros

### ISSUE THREAD

**Issue by ajfv** [J0hnG4lt/ClienteServidor#2]
En el código se asume que caben en un `int`, pero el tamaño máximo es 1000 caracteres. Deberíamos preguntarle a la profe que podemos asumir sobre esos identificadores, a ver como que tipo lo guardamos. Si son numéricos no hace falta el strlen, solo vemos con strtol si hubo overflow.

**Comment by J0hnG4lt** [comment]
Vale. Si le preguntas ahorita me avisas. Igual le enviaré un correo con
preguntas esta noche.

**Comment by ajfv** [comment]
Quedamos con Mireya en que da igual, con tal se ponga en el informe
